### ISSUE TITLE
SEP 048 -- Enhance Combinatorial Derivations

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SEPs#103]
In SBOL3, combinatorial derivations can also represent things like the design of an experiment, e.g., test strains A, B, and C in media X, Y, and Z. Currently, however, it is not able to take advantage of the full succinctness offered by the new Feature class. This SEP proposes a generalization of the CombinatorialDerivation class to allow direct use of all features and measures.

https://github.com/SynBioDex/SEPs/blob/master/sep_048.md

**Comment by cjmyers** [comment]
This one looks really useful to me.
