### ISSUE TITLE
SEP 050: Remove Namespace Object

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SEPs#105]
After the approval of SEP 047 that reversed the direction of the namespace reference, the Namespace object become obsolete.  It also create some problems in the special case it requires for URIs, so we are proposing to remove the object.

Full SEP at: https://github.com/SynBioDex/SEPs/blob/master/sep_050.md

**Comment by jakebeal** [comment]
See discussion on specification issue: https://github.com/SynBioDex/SBOL-specification/issues/422
