### ISSUE TITLE
SEP 053: Use existing SO terms for Feature orientation

### ISSUE THREAD

**Issue by jamesscottbrown** [SynBioDex/SEPs#111]
The full SEP is [here](https://github.com/SynBioDex/SEPs/blob/master/sep_053.md); it is intended to address https://github.com/SynBioDex/SBOL-specification/issues/455.

## 1. Rationale <a name="rationale"></a>

The [current specification](https://sbolstandard.org/docs/SBOL3.0specification.pdf) (v3.0.1) states that:

> If a Feature object has an orientation, then it MUST come from Table 5

Table 5 lists `http://sbols.org/v3#inline` and `http://sbols.org/v3#reverseComplement`.

However, we have a general principle of reusing existing identifiers where possible, and only introducing our own identifiers when necessary.

Sequence Ontology contains the relevant terms as [`SO:0001030` (forward)](http://www.sequenceontology.org/browser/current_release/term/SO:0001030) and [`SO:0001031` (reverse)](http://www.sequenceontology.org/browser/current_release/term/SO:0001031); we should therefore be preferentially using these terms.

## 2. Specification

Replace:

>  Table 5 provides a list of REQUIRED orientation URIs. If a Featureobject has an orientation, then it MUST come from Table 5

With:

> If a Feature object has an orientation, then it is RECOMMENDED that it come from Table 5; for reasons of backwards compatibility it MAY instead come from Table 6.

Table 5 would list the SO terms [`SO:0001030` (forward)](http://www.sequenceontology.org/browser/current_release/term/SO:0001030) (`https://identifiers.org/SO:0001030`) and [`SO:0001031` (reverse)](http://www.sequenceontology.org/browser/current_release/term/SO:0001031) (`https://identifiers.org/SO:0001030`). The caption would be "RECOMMENDED URIs for the orientation property".

Table 6 would list the terms listed Table 5 of the current specification (`http://sbols.org/v3#inline` and `http://sbols.org/v3#reverseComplement`). The caption would be "Permitted alternative URIs for the orientation property. The URIs listed in Table 5 are preferred and SHOULD be used instead where possible".

**Comment by cjmyers** [comment]
This seems like a reasonable change to me.

**Comment by PrashantVaidyanathan** [comment]
This has been incorporated into the latest Specification: 3.0.1
