### ISSUE TITLE
SEP 056 -- Generalize from URIs to IRIs

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SEPs#121]
This SEP proposes to change the SBOL specification from URIs to IRIs.

URIs have largely been generalized to IRIs, including in RDF 1.1. SBOL should support IRIs as well.
A number of tools already support IRIs implicitly via their use of RDF libraries, and this will endorse that practice.

Full draft in: https://github.com/SynBioDex/SEPs/blob/master/sep_056.md

**Comment by cjmyers** [comment]
Do we really want to support IRIs or simply add international alphabetic characters in URIs?

**Comment by jakebeal** [comment]
When RDF 1.1 was published in 2014, it made IRIs the standard. Any system that supports RDF 1.1 (which is basically all modern RDF software) therefore also supports IRIs.

 If we want to support anything _less_ than full IRIs, it will require a lot of work on the part of library implementers to downgrade the libraries that are being used.

**Comment by cjmyers** [comment]
Discussed in the SBOL3 working group.  Consensus was this is supported for by new libraries and triplestores, so it should be safe to change.
