### ISSUE TITLE
SEP 002 -- SEP Template Document

### ISSUE THREAD

**Issue by graik** [SynBioDex/SEPs#2]
# SEP 002 -- SEP Template Document <replace title with your own>

< Note 1: remove/replace all instructions given within "< >" >
< :exclamation: Note 2: you really need to look at this in raw / editing mode :smiley:  >
< Note 3: download the raw template from: https://raw.githubusercontent.com/SynBioDex/SEPs/master/sep_002_template.md >

| SEP | <leave empty> |
| --- | --- |
| **Title** | SEP Template Document <replace with your short descriptive title (44 character max)> |
| **Authors** | <Author1 name (author1mail at xxmail com), Author2 name (author mail at yyy com)> |
| **Editor** | <leave empty> |
| **Type** | Process <choose from: Process OR Data Model> |
| **SBOL Version** | <SBOL version this proposal should apply to; remove line if Type==Process> |
| **Replaces** | <list SEP(s) this proposal would replace, otherwise remove line. E.g. SEP #1> |
| **Status** | Draft |
| **Created** | 08-Oct-2015 <current date> |
| **Last modified** | 08-Oct-2015 <leave empty if this is the first submission> |
## Abstract

< insert short summary >
## Table of Contents  <remove TOC if SEP is rather short>
- [1. Rationale](#rationale) <or, if you prefer, 'Motivation'>
- [2. Specification](#specification)
  - 2.1 optional sub-point
  - 2.2 optional sub-point
- [3. Example or Use Case](#example)
- [4. Backwards Compatibility](#compatibility)
- [5. Discussion](#discussion)
  - 5.1 discussion point
  - 5.2 discussion point
- [References](#references)
- [Copyright](#copyright)
## 1. Rationale <a name="rationale"></a>

< insert motivation / rational, keep it brief >
## 2. Specification <a name="specification"></a>

< give detailed specification, can be split up into more than one section if useful >
< refer to other SEPs like this: This SEP is much better than SEP #1>
### 2.1 optional sub-point

< sub-divide specification section if useful >
### 2.2 optional sub-point

< sub-divide specification section if useful >
## 3. Example or Use Case <a name='example'></a>

< Describe brief examples or use cases >
## 4. Backwards Compatibility <a name='compatibility'></a>

< discuss compatibility issues and how to solve them; remove this section if this doesn't apply >
< e.g. in case of procedure SEP >
### 5.1 discussion point

< Summarize discussion, also represent dissenting opinions >
## References <a name='references'></a>

< list references as follows >

< refer to these references in the text as, e.g. [SBOL](http://sbolstandard.org) or [1](https://www.python.org/dev/peps/pep-0001) >
## Copyright <a name='copyright'></a>

< SEPs should generally be public domain; replace names as needed.  If necessary, change to a different license (typically another CC license) >

<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="sbolstandard.org">
    <span property="dct:title">SBOL developers</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">SEP 002</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="US" about="sbolstandard.org">
  United States</span>.
</p>

**Comment by graik** [comment]
Since normal users won't have editing rights on this issue tracker, I have checked in a copy of the raw markdown file as `sep_002_template.md`.

**Comment by jakebeal** [comment]
Labelling as CC0 rather than public domain for better legal compatibility, per discussion with Raik.

**Comment by graik** [comment]
Added "Editor" field to preamble. Following Michal's suggestion (see SEP #1).

**Comment by graik** [comment]
changed Type : Procedure -> Type: Process

**Comment by graik** [comment]
Voting closed on March 10th 2016. This SEP was accepted together with SEP #1.
Votes: 25
Accept: 25

**Comment by palchicz** [comment]
Closing in accordance with changes to SEP issue tracking rules detailed in SEP 001 https://github.com/SynBioDex/SEPs/commit/bcbbcab01a2b01d5055fc55d03c949fb227e37d2#diff-44cec2aabf4c066f9a54ac4ef6634b9b
