### ISSUE TITLE
SEP 009 -- SBOL Provenance

### ISSUE THREAD

**Issue by udp** [SynBioDex/SEPs#24]
This SEP introduces terms and classes from the PROV-O ontology, allowing rich expression of provenance in SBOL.

Proposal document: https://github.com/SynBioDex/SEPs/blob/master/sep_009.md

**Comment by graik** [comment]
tentatively assigned to SBOL version 2.2

**Comment by jakebeal** [comment]
What is left to do from this? I thought we'd added provenance in SBOL 2.1?

**Comment by cjmyers** [comment]
Yes, it has been incorporated as a Best Practice.  I think you can close this.  Goksel?

**Comment by palchicz** [comment]
Closing in accordance with changes to SEP issue tracking rules detailed in SEP 001 https://github.com/SynBioDex/SEPs/commit/bcbbcab01a2b01d5055fc55d03c949fb227e37d2#diff-44cec2aabf4c066f9a54ac4ef6634b9b
