### ISSUE TITLE
SEP 010 -- simplify description of sequence features and sub-parts

### ISSUE THREAD

**Issue by graik** [SynBioDex/SEPs#25]
This proposal aims to clearly separate and simplify the description of part - subpart relations on the one hand, and the annotation of (genbank-style) sequence features on the other hand. 

Proposal document: https://github.com/SynBioDex/SEPs/blob/master/sep_010.md

**Comment by graik** [comment]
Updated after very productive discussion at COMBINE breakout session. The current formulation of the SEP prescribes changes for SBOL 2.2 (adding and deprecating fields) **and** for SBOL 3.0 (removing fields and renaming `SequenceAnnotation` to `SequenceFeature`.

**Comment by jakebeal** [comment]
On discussion, the editors have determined that this is an SBOL 3.0 issue, because as soon as it is possible to write a file that does *not* have a SequenceAnnotation --> Component link, then it will not be possible for SBOL 2.0 or SBOL 2.1 tools to correctly interpret the location.  This missing information means it is *not* a backward compatible change.

**Comment by NeilWipat** [comment]
Update from COMBINE 2018

Needs more discussion

**Comment by cjmyers** [comment]
This was already approved, but the remove of Component link from SA has not been executed yet or the adding or Location to Component. These were deferred to SBOL 3.

**Comment by bbartley** [comment]
Once this SEP is implemented, can we relax the requirement that the `definition` property is required?  I would like that property to be optional.  For example, I would like to be able to represent sub-structure using only `Components` and their respective child `Locations`.

**Comment by cjmyers** [comment]
That would definitely need to be a different SEP.  Not sure I'm excited about this idea.  I guess it could allow you to avoid creating dummy CDs when constructing a design, which could be good.  Not sure what the difference would be though in simply using SequenceAnnotations with Roles instead.  I think that you end up in the same place.
