### ISSUE TITLE
SEP 011 -- Specify DNA / RNA topology with type fields

### ISSUE THREAD

**Issue by igemsoftwareadmin** [SynBioDex/SEPs#26]
This proposal suggests to use the ComponentDefinition.type field in order to express whether DNA (RNA) is circular or linear and double stranded or single stranded. In contrast to the alternative proposal (SEP 008), this does not require changes to the data model.

The proposal text can be found here
https://github.com/SynBioDex/SEPs/blob/master/sep_011.md

Following discussion on the mailing list and among editors, this SEP has been adopted for SBOL 2.1 without a formal vote.

**Comment by graik** [comment]
Accepted by the editors. A vote was not deemed necessary as this is not any longer a data model change. Please feel free to re-raise this issue on sbol-dev (any 2 members of sbol-dev can ask for an SEP to be voted on.)

**Comment by palchicz** [comment]
Closing in accordance with changes to SEP issue tracking rules detailed in SEP 001 https://github.com/SynBioDex/SEPs/commit/bcbbcab01a2b01d5055fc55d03c949fb227e37d2#diff-44cec2aabf4c066f9a54ac4ef6634b9b
