### ISSUE TITLE
SEP 012 -- Any cardinality for Identified.wasDerivedFrom

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SEPs#27]
This SEP allows Identified.wasDerivedFrom to have multiple sources of derivation.

Proposal document: https://github.com/SynBioDex/SEPs/blob/master/sep_012.md

**Comment by cjmyers** [comment]
I remember this discussion with Goksel now.  When you say convert an NCBI sequence to SBOL, you can link the NCBI record using wasDerivedFrom, then optionally include an Activity object to indicate how it was derived.  If you want to say that this SBOL object was actually derived from multiple records, it is best to use the Usage object as it enables you to specify a Role for each object.  So, for example if you want to say this Sequence object was derived from another Sequence object and an NCBI record, you could create two Usage objects, one with Role “original record” and another with Role “previous SBOL record”.  You can still include one of these in the wasDerivedFrom field, if you like.

Chris

**Comment by palchicz** [comment]
Closing in accordance with changes to SEP issue tracking rules detailed in SEP 001 https://github.com/SynBioDex/SEPs/commit/bcbbcab01a2b01d5055fc55d03c949fb227e37d2#diff-44cec2aabf4c066f9a54ac4ef6634b9b
