### ISSUE TITLE
SEP 015 -- Simplification of SBOL class names

### ISSUE THREAD

**Issue by graik** [SynBioDex/SEPs#32]
This SEP proposes to rename `ComponenDefinition` to `Component` and the current `Component`(instance) to `SubComponent` to better reflect the purpose of these classes and in order to to mirror actual usage of these terms within the SBOL community. 

see evolving document in SEP github repo:
https://github.com/SynBioDex/SEPs/blob/master/sep_015.md

**Comment by NeilWipat** [comment]
Update of COMBINE 2018

Needs discussion in the context of SBOL3

**Comment by udp** [comment]
This change, along with SEP 025, is partially implemented in my fork at http://github.com/udp/SBOL-specification
