### ISSUE TITLE
SEP 018 -- Attachment

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/SEPs#39]
This proposal introduces the Attachment class as a general container for linking external data files, such as experimental data.  Please review the full proposal at https://github.com/SynBioDex/SEPs/blob/master/sep_018.md

**Comment by palchicz** [comment]
Closing in accordance with changes to SEP issue tracking rules detailed in SEP 001 https://github.com/SynBioDex/SEPs/commit/bcbbcab01a2b01d5055fc55d03c949fb227e37d2#diff-44cec2aabf4c066f9a54ac4ef6634b9b
