### ISSUE TITLE
SEP 019 -- Using SBOL to model the Design-Build-Test-Learn Cycle

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SEPs#43]
This proposal introduces the Implementation and Attachment classes as well as a general procedure for linking design-build-test objects using PROV-O. Please review the full proposal at https://github.com/SynBioDex/SEPs/blob/master/sep_019.md

**Comment by palchicz** [comment]
Closing in accordance with changes to SEP issue tracking rules detailed in SEP 001 https://github.com/SynBioDex/SEPs/commit/bcbbcab01a2b01d5055fc55d03c949fb227e37d2#diff-44cec2aabf4c066f9a54ac4ef6634b9b
