### ISSUE TITLE
SEP 020 -- Linking experimental results with Biological clones and replicates

### ISSUE THREAD

**Issue by graik** [SynBioDex/SEPs#47]
This SEP proposes improvements over SEP 19 which it hopes to replace.  It introduces an Implementation class and prescribes how experimental results and workflow data can be recorded. The main difference is a somewhat simplified data model that relies less on prov-O (all use of providence ontology remains optional) and provides a more direct link from Experiment via Clone (implementation) to Sequence (ComponentDefinition). Moreover, although it supports the somewhat idealistic Design - Build - Test paradigm, the proposal tries to focus on more practical everyday use cases.

Since SEP 20 is really a fork of SEP 19, the authors of 19 should probably be added here. Please speak up to complain.

Please review the proposal at:
https://github.com/SynBioDex/SEPs/blob/master/sep_020.md

**Comment by palchicz** [comment]
Update as of COMBINE 2018

This was voted on and rejected in favor of SEP 19.

**Comment by palchicz** [comment]
Closing in accordance with changes to SEP issue tracking rules detailed in SEP 001 https://github.com/SynBioDex/SEPs/commit/bcbbcab01a2b01d5055fc55d03c949fb227e37d2#diff-44cec2aabf4c066f9a54ac4ef6634b9b
