### ISSUE TITLE
SEP 023 -- Add a best practice to associate at most one sequence with a ComponentDefinition

### ISSUE THREAD

**Issue by udp** [SynBioDex/SEPs#55]
Full details in: https://github.com/SynBioDex/SEPs/blob/master/sep_023.md

**Comment by udp** [comment]
Revoked

**Comment by jakebeal** [comment]
Copy of rationale for withdrawing into the issue from the SEP, for easier reference:
> This SEP has been revoked in favour of an upcoming SEP to add a link from locations to sequences, which would avoid the ambiguity of SequenceAnnotations.
>
> In discussion we identified cases where multiple sequences are appropriate:
> * Different encodings of the same thing (e.g. smiles and inchi)
> * DNA sequence + methylation patterns

**Comment by palchicz** [comment]
See comments above for rationale for closing

**Comment by palchicz** [comment]
See comments above for rationale for closing
