### ISSUE TITLE
SEP 026 -- Add a link from Location to Sequence

### ISSUE THREAD

**Issue by udp** [SynBioDex/SEPs#59]
Full details in: https://github.com/SynBioDex/SEPs/blob/master/sep_026.md

**Comment by palchicz** [comment]
Some more background on this SEP would be helpful. Can the SEP include examples of when a ComponentDefinitions would have multiple Sequences? It's unclear if this is referring to the case where the sequences are of different versus the same encoding. If of the same encoding, is this meant for when sequence annotations are being used to describe features. What about the case of discontinuous regions?

**Comment by cjmyers** [comment]
I let @udp update the SEP, but I can add a bit more context here.  In a discussion at HARMONY, we identified some cases where multiple sequences are appropriate, such as:

* Different encodings of the same thing (e.g. smiles and inchi)
* DNA sequence + methylation patterns

The encoding may be different, but it is not clear which Sequence a SequenceAnnotation refers to.  This is the reason this reference is needed.  In the case of discontinuous regions, I would assume that each Location making up the region would refer to the same Sequence.  However, this is not required.  So, you could also have an annotation that annotates two sequences simultaneously to indicate where the same feature shows up in each sequence.

**Comment by cjmyers** [comment]
Doesn’t hurt to explain why the fix is to add the reference rather than removing the multiple sequences.  It was indeed a path we considered first.

**Comment by palchicz** [comment]
@cjmyers That explanation makes sense. Just to repeat what you are saying, the use case this is trying to get at is when there are multiple encodings. 

@udp Maybe to clarify my question a bit more, the standard leaves open the possibility for multiple sequences with the same encoding (from section 7.7). 

> If a ComponentDefinition refers to more than one Sequence with the same encoding, then the elements of these Sequence objects SHOULD have equal lengths.

I guess that's the scenario I want to understand more, and if this proposed change applies.

**Comment by cjmyers** [comment]
Ah, that's a good question.  I think that the best practice would be that if no sequence reference is provided that this means the SequenceAnnotations apply to all sequences at the same specified location.  If only one Sequence is being annotated, then one should provide a sequence reference.

**Comment by palchicz** [comment]
Awesome! Thanks @cjmyers for the explanation.

This SEP doesn't sound controversial to me. I can send out an email to the DEV list reminding people to take a look after the SEP is amended with some of the background/motivation material we've just discussed. If no one dissents, I'll move it to a vote.

**Comment by cjmyers** [comment]
Sounds good. @udp please update as per this thread.

**Comment by palchicz** [comment]
@cjmyers and @udp one final question. Would the new `sequence` property be required or optional. A reading of the SEP makes it sound like it would be required, but I wanted to double check.

**Comment by cjmyers** [comment]
It must be optional otherwise this would need to be SBOL 3.  We do not allow SBOL 2.x changes to invalidate earlier versions of SBOL 2.y where y <= x.

**Comment by palchicz** [comment]
Closed with commit acd4ba958f70c7bcc32a72637feda0eec701425c
