### ISSUE TITLE
SEP 028 -- Measurements/Parameters and Units

### ISSUE THREAD

**Issue by NeilWipat** [SynBioDex/SEPs#62]
Update as of COMBINE 2018

Nic is going to amend the language so that the description of our use of OM matches that of our use of PROV-O.

**Comment by palchicz** [comment]
link to SEP https://github.com/SynBioDex/SEPs/blob/master/sep_028.md

**Comment by palchicz** [comment]
See: https://github.com/SynBioDex/SBOL-specification/pull/212
