### ISSUE TITLE
 .NET Standard support

### ISSUE THREAD

**Issue by hez2010** [SynBioDex/SEPs#72]
Can you add support for .NET Standard?
Then we can use libSBOL in .NET Core and .NET Framework apps.

Thanks.

**Comment by jakebeal** [comment]
Not being familiar with .NET myself: would .NET support require building a new library, or is this something that can be added to libSBOL in a fairly lightweight manner?

**Comment by jakebeal** [comment]
(ps: I have removed the "SEP" marker, since that is generally used for changes to the specification, and this is a request for changes to the library)

**Comment by hez2010** [comment]
@jakebeal 
On .NET we use P/Invoke (Platform Invoke) to wrap C++ methods so that .NET can invoke methods in C++ shared libraries directly without changing C++ code.

For example, an export function in a C++ shared library is:
```cpp
extern "C" int test(int a, const char* b); // assume that its ordinal is 0
```
We can write in C#:
```csharp
[DllImport("./xxx.so", EntryPoint = "#0", CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Cdecl)] // the EntryPoint can be #ordinal or function name, so we can write either EntryPoint = "#0" or EntryPoint = "test"
static int Test(int a, [MarshalAs(UnmanagedType.LPStr)] string b);
```
And we can use it by calling Test(int, string) in .NET Standard.

**Comment by jakebeal** [comment]
Sounds like it could be implemented in much the same way as pySBOL currently wraps libSBOL. Would you be interested in building that library?  I expect the community would be happy to endorse it once it exists!

**Comment by hez2010** [comment]
I could to do it but it depends on my free time.

**Comment by jakebeal** [comment]
As with all of us. :-)

**Comment by cjmyers** [comment]
I think you probably want to log this issue with our C++ library issue tracker, here:

https://github.com/SynBioDex/libSBOL <https://github.com/SynBioDex/libSBOL>

**Comment by hez2010** [comment]
Sounds great.

**Comment by palchicz** [comment]
closing this since it is now covered in https://github.com/SynBioDex/libSBOL/issues/213
