### ISSUE TITLE
SEP 034 -- Relax rules on interaction participant ownership

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SEPs#79]
Proposal by James and Bradley on allowing interactions to point to transitively included FunctionalComponents: https://github.com/SynBioDex/SEPs/blob/master/sep_034.md

**Comment by jakebeal** [comment]
I went down a similar path in SEP 037.  I ended up adding a full reference class there, however, since otherwise I don't see any way to distinguish between different ComponentInstances in two different Module or FunctionalComponent objects referring to the same definition.

**Comment by udp** [comment]
Revoked in favour of SEP 037
