### ISSUE TITLE
SEP 036 -- Externally Grounded Components

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SEPs#81]
This proposal adds an option for a `ComponentInstance` to use external definitions in databases like CHEBI or UniProt.

https://github.com/SynBioDex/SEPs/blob/master/sep_036.md

**Comment by cjmyers** [comment]
Another possible solution to this issue would be to remove the validation rule that requires the definition to point to a ComponentDefinition object (sbol-10604).  Note that already this is allowed in a sense, since a not SBOL object being referred to cannot be fetched and validated to be a ComponentDefinition.  

My concern with this proposal though is that in either case that if you cannot dereference the referred to definition, then you will not know the type of the object being referred to.  I would be more comfortable with this proposal if we added a type field to the Component object, which, if used, should be consistent with the type of the object referred to by the definition/externalDefinition.

**Comment by jakebeal** [comment]
I have updated this based on @cjmyers concern and the recent discussion and changes for SEP 037.  The new proposal creates a new `ExternalReference` class with type and role information, as a sibling to `ComponentInstance` rather than changing the `ComponentInstance` class.  I believe this is conceptually cleaner and simpler, but it does mean this is necessarily an SBOL 3 upgrade.

**Comment by cjmyers** [comment]
I think Roles should move up to the parent class, which simplifies this a bit.  I think we should decide on SEP 025 and SEP 037 first, since this in some sense builds on SEP 037.

**Comment by jakebeal** [comment]
Exactly: when SEP 025 and SEP 037 settle, it will imply whether the role field gets shared or not. I expect that type will stay here, though, since it's not on either proposed sibling.

**Comment by jakebeal** [comment]
I've updated this with my understanding of the likely SBOL 3 class hierarchy, shared with SEP 037 and SEP 043.

**Comment by cjmyers** [comment]
I'm not excited about subComponent being an abstract class.  This means the new name that we chose for Component (i.e., SubComponent) would never appear in serialization.  Abstract classes do not.  

In any case, I think this can be done much more simply.  Namely, add an optional types field to SubComponent, and modify the following validation rule from:

"The URI contained by the definition property MUST refer to a ComponentDefinition object."

to read instead:

"If the URI contained by the definition property refers to an object in the SBOL namespace, then it MUST refer to a ComponentDefinition object."

We might also want an additional best practice that says something like:

"If the URI contained by the definition property does not refer to an object in the SBOL namespace, then there SHOULD be at least one type specified."

**Comment by jakebeal** [comment]
The naming question can be dealt with separately if needed: let's focus on the data representation first.  

I am concerned that in your alternate proposal "refers to an object in the SBOL namespace" might be difficult to verify.  For example, if I give you a URL to some external database, how do you figure out if it's going to resolve to a CHEBI value or a protein structure or an SBOL object stored there?

**Comment by cjmyers** [comment]
Same problem with ANY URI reference we have that we cannot dereference.  This is why these are weak validation rules in the first place.  Namely, if you can dereference, then you can check its type, if not, then you cannot.

**Comment by jakebeal** [comment]
Which is exactly why I thought it would be useful to have some way of explicitly saying: "this points to something that is not SBOL". 

Speaking of such: a third possibility would thus be to add a Boolean "external" property.  

Note also that for external components, there is no well-defined meaning for roleIntegration and sourceLocation fields. As such, I am concerned that either your alternate proposal or the "external" property proposal are effectively simulating something that is more cleanly represented by a class distinction.

**Comment by jakebeal** [comment]
Concentrating the naming discussion from SEP 037 and SEP 043 threads: @cjmyers has proposed making the abstract parent class `ComponentInstance` and the existing child `SubComponent`. I am fine with this proposal.

Can we hear some additional voices besides me, Chris, and Raik?

**Comment by jakebeal** [comment]
I've pushed an updated version of all three proposals that makes ComponentInstance the abstract class and SubComponent the class analogous to Component/FunctionalComponent.

**Comment by cjmyers** [comment]
Fine with class distinction after the name swap.
