### ISSUE TITLE
SEP 039 -- Making SBOL more Semantic Web friendly

### ISSUE THREAD

**Issue by goksel** [SynBioDex/SEPs#87]
This SEP addresses some of the issues related to the naming of SBOL entities and using URIs to adopt existing Semantic Web best practices. It also recommends a fully-graph based serialisation for SBOL documents.

The SEP is available at: https://github.com/SynBioDex/SEPs/blob/master/sep_039.md

**Comment by jakebeal** [comment]
@goksel Can we have a restriction added to make it so there is no more than one sbol object type when there is more than one rdf:type?

If this is added, this seems otherwise fine.

**Comment by cjmyers** [comment]
See validation rule sbol-10228: An Identified object must have no more than one rdfType property in each of the “http://sbols.org/v2#” and “http://www.w3.org/ns/prov#” namespaces. 14 Reference: Section 7.4 on page 17

So, I think we are actually okay on this one.

**Comment by hasanbaig** [comment]
If there is no further discussion needed, we move this SEP for voting as well, shall we?

**Comment by jakebeal** [comment]
Yes, this can be moved forward.
