### ISSUE TITLE
SEP 040 -- Change BioPAX to SBO

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SEPs#88]
The `Component` field `type` is currently REQUIRED to use a BioPAX term, which is limiting and does not match with the SBO terms used on Interactions and Participations and in SBOL Visual. This SEP proposes changing to SBO, following the same mapping previously used with SBOL Visual.

The SEP is available at: https://github.com/SynBioDex/SEPs/blob/master/sep_040.md

**Comment by cjmyers** [comment]
This seems like a good idea to me.  This is a better defined ontology.

**Comment by udp** [comment]
Implemented in SBOL3 draft
