### ISSUE TITLE
SEP 043 -- Local SubComponents

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SEPs#91]
In some cases, SubComponents are used for local placeholders or composites that only really make sense within the context of their parent Component, being defined in terms of their relationships with other SubComponents. In this case, it may be advantageous to be able to represent the local composite without giving it a complete definition. This SEP presents a method for doing so via a new LocalSubComponent subclass of SubComponent.

Full SEP available at: https://github.com/SynBioDex/SEPs/blob/master/sep_043.md

**Comment by cjmyers** [comment]
I'd actually like to see the UML for this for SBOL3.  There are many changes being proposed that affect the structure of Components, and I would like to see the final UML being proposed. 

The idea of this proposal seems fine to me.

**Comment by graik** [comment]
This actually relates to SEP 42 that I just criticized  :grimacing: 

SubComponent + role is IMO the perfect point for the definition of "missing" or "yet undefined" parts. In fact, if we have a component with only empty subComponents (but with roles) this is basically a class template. If there is only some gaps, it makes it obvious to any tool that these still need filling before the design is complete.

The question is, do we need a special sub-class for this? Would it not be enough to simply make "definition" in `SubComponent` optional? This would have the advantage that designs could organically grow until all the missing pieces are filled in (potentially by different sofware tools) without the need of on-the-fly type changes from one subComponent class to another.

**Comment by jakebeal** [comment]
@graik I note this possible alternative in the Discussion section of the SEP:

> A potential alternative implementation is to make the definition field of ComponentInstance optional. This would avoid adding a new class, but prevent distinguishing between a SubComponent with a missing definition (an error) and a SubComponent that is intentionally not provided with a definition.

I'm fine with either approach --- the question is which side of the tradeoff the community prefers.

**Comment by cjmyers** [comment]
I prefer simpler, so I would go with making definition an optional field AND adding an optional type field to SubComponent.  Perhaps, we should also add a typeIntegration with similar functionality as roleIntegration.

**Comment by jakebeal** [comment]
I've updated this with my understanding of the likely SBOL 3 class hierarchy, shared with SEP 036 and SEP 037.

**Comment by cjmyers** [comment]
Once again, I don't like SubComponent as an abstract class.  I think it is much simpler to have a single SubComponent class with definition optional.  

That being said, I could find this UML acceptable if you reverse the SubComponent and ComponentInstance class names.  Hmm, I guess the same could be said for SEP 036 and 037.

**Comment by jakebeal** [comment]
I don't really care about the names as long as they end up with something reasonable, so maybe we can get some other folks to weigh in and see which of the two options we want to move forward for a vote.

**Comment by cjmyers** [comment]
Naming is more important than you seem to think on this.  ComponentInstance is an abstract class in SBOL2, but Component is a concrete class.  Your proposal is flipping this unnecessarily.  To me, this is a non-starter.

**Comment by jakebeal** [comment]
The naming discussion is spreading across three SEPs: I've formulated SEP 037 and SEP 043 so that they assume the result of a naming choice in SEP 036. Can we please focus the naming discussion in that thread?
