### ISSUE TITLE
SEP 045 -- Expand set of SequenceConstraint relations

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SEPs#93]
The precedes relationship covers only one of the seven basic relationships of standard interval algebra. This SEP proposes to add the other six (along with some key unions) and to clarify the definition of precedes.

Full SEP available at: https://github.com/SynBioDex/SEPs/blob/master/sep_045.md

**Comment by cjmyers** [comment]
This seems fine to me.  My only question is whether the list is complete.  Has anything been missed?  Should adding new restriction types go through the same SEP process, or can we think about this like adding terms to an ontology.

BTW: restrictionType is the one item that we did not "restrict"  we did allow other restriction types already, but we are here adding new ones in the SBOL namespace, which is good.

**Comment by jakebeal** [comment]
The 7 base relations are canonically complete, and the two unions added are obvious clusterings.  There are many other potential unions, but they should not be handled by adding terms, since they are combinatorial: in the future, we may wish to consider how to express "OR" constraints, but that's not being requested now.

**Comment by cjmyers** [comment]
Ok, sounds good to me.

**Comment by jakebeal** [comment]
I have expanded the description of this SEP to better explain how it will interact with SEP 037 and SEP 045.

**Comment by udp** [comment]
Implemented in SBOL3 draft
